##
# This file contains all the possible configuration properties.
#
# Please note, that some of them have default values and some don't
##

# The environment associated with this configurations. Accepted values are (case insensitive): dev, development, prod, production.
# Default value is "development"
environment: "dev|development|prod|production"

# Defines how the application logging works.
logger:

  # Define the main application logger settings.
  main: 
  
    # The logger message format. Accepted values are (case insensitive): text, json. 
    # If none is present the default "text" is considered.
    format: "text|json"

    # The logger level. Accepted values are (case insensitive): panic, fatal, error, warn, warning, info, debug, trace. 
    # If none is present the default "info" is considered.
    level: "panic|fatal|error|warn|warning|info|debug|trace"

    # The directory where all log files are placed. 
    # If it does not exist its creation will be attempted. Default value is "./logs".
    dir:

    # The name of the log file name. 
    # Default value is "basic-go-rest-api.log"
    file-name:

    # The default prefix associated with this logger; will be added along with all messages.
    # Default value is "main".
    prefix: "main"

    # Boolean value that if true will also print the log messages to console; otherwise the messages can be found only in the log files. 
    # Default value is "false".  
    with-console: false

      # Define the application access logger settings.
  access: 
  
    # The logger message format. Accepted values are (case insensitive): text, json. 
    # If none is present the default "text" is considered.
    format: "text|json"

    # The logger level. Accepted values are (case insensitive): panic, fatal, error, warn, warning, info, debug, trace. 
    # If none is present the default "error" is considered.
    level: "panic|fatal|error|warn|warning|info|debug|trace"

    # The directory where all log files are placed. 
    # If it does not exist its creation will be attempted. Default value is "./logs".
    dir:

    # The name of the log file name. 
    # Default value is "access.log".
    file-name:

    # The default prefix associated with this logger; will be added along with all messages.
    # Default value is "access".
    prefix: "access"

    # Boolean value that if true will also print the log messages to console; otherwise the messages can be found only in the log files. 
    # Default value is "false".  
    with-console: false

# Defines how the server works.
server:

  # HTTP settings.
  http:
    
    # The port that the server listens on.
    # Default value is "8080".
    port: 8081

    # The server request read timeout (in seconds).
    # Default is "10"
    read-timeout: 

    # The server response write timeout (in seconds).
    # Default is "10"
    write-timeout: 

# Defines where the serve connect to as a storage.
storage:

  # The storage type that must be used. Accepted values are (case insensitive): local, mongo.
  # Default value is "local".
  type: "local|mongo"

  # Defines the local storage settings.
  local:

    # The location where the local storage must be created and used from.
    # Default value is "local-storage/boltdb".
    name: "local-storage/boltdb"

  # Defines the mongoDB storage settings. Will be used only if storage.type="mongo"
  mongo:

    # The mongoDB URI.
    # No default value is provided.
    uri: "mongodb://localhost:27017"

    # The database name.
    # No default value is provided.
    name: "testdb"

    # The properties collection name.
    # No default value is provided.
    properties-collection: "properties_collection"