logger:
  main: 
    with-console: true
  access: 
    with-console: true

server:
  http:    
    port: 8081    

storage:
  type: local
  
  bolt:
    name: "local-storage/testdbbolt"   

  mongo:
    uri: "mongodb://localhost:27017"
    name: "testdb"    