logger: 
  application-log-console: true

server:
  http:    
    port: 8081    

storage:
  mongo:
    uri: "mongodb://localhost:27017"
    name: "testdb"
    properties-collection: "properties_collection"